### ISSUE TITLE
is there a need for write.inp() ?

### ISSUE THREAD

**Issue by bradleyjeck** [bradleyjeck/epanetReader#12]

**Comment by woohn** [comment]
I think write.inp function can be useful api to the simulation of different scenarios. For instance, you can generate different demand usage for future. Also, you can use GUI for simulation if you modified inp file someway.

**Comment by bradleyjeck** [comment]
Thanks for the feedback @woohn. Would you be interested to contribute such a function?  I'm also interested in other possible features.
