### ISSUE TITLE
parse rpt files created by epanet gui 

### ISSUE THREAD

**Issue by bradleyjeck** [bradleyjeck/epanetReader#26]
Following up on this discussion thread: http://community.wateranalytics.org/t/epanetreader-r-package-error/250

It seems the simulation report created in the windows gui using Report > Full is not read by epanetReader as it contains page breaks.   These breaks appear regardless of the contents of the .inp file.  

Look at updating the rpt parser to handle this case.

**Comment by bradleyjeck** [comment]
Hi @gintaem - Thanks for forking the project.  You might be interested in the branch gui-rpt-files . . . Happy to have contributions/feedback/discussion.

**Comment by gintaem** [comment]
Hey @bradleyjeck , Thank you for your message. I'll have a look on it. I'm no programmer, but if i have recommendations i'll let you know.

kind regards,
Markus

**Comment by bradleyjeck** [comment]
Hi @gintaem -  I have now added the functionality for reading rpt file from the gui to the main branch of the project.   Would you mind trying it out to see if it works for you? 

You can install the development version by first installing the devtools package. Then install epanetReader from github like this. 

```
devtools::install_github("bradleyjeck/epanetReader")
```

From there the read.rpt() function should work on a file generated by the menu command Report > Full in the GUI.

**Comment by gintaem** [comment]
Dear @bradleyjeck ,
thanks in advance! I'll try it out as soon as possible and give you feedback if it works. I just have to fix my Rstudio and Git ...

kind regards,
Markus

**Comment by gintaem** [comment]
Hi @bradleyjeck ,

I just installed the epanetReader from Github and tried reading input files as well a rpt files but  while reading the inp File an error occured:
When i tried reading the inp. file I received following error:
_Error in .lineRange(tag, allLines) : 
  [REACTIONS] appeared more than once_

Reading the GUI-created rpt file worked well! 
Seems as the rpt reader works now for both, command line based reports and GUI-created reports.

I'm not quite sure if the inp file reading error is due to the git testfile (is it just for testing the rpt file reader?) 

Regards,
Markus

**Comment by bradleyjeck** [comment]
Glad you were able to install, and have success reading the gui rpt file!  

The inp File error is probably because the REACTIONS section appears twice in the inp file.  For some reason inp files exported by the GUI have this heading twice -- once with an empty section.   Try opening the inp file in in a text editor and removing the [REACTIONS] heading that is over an empty section.

What might a more informative error message look like?

**Comment by gintaem** [comment]
ok, 
When i tried the epanetReader the first time everything except the rpt reading went fine, that's why i thought there is something wrong now.
yes you were right. the inp file had two headings named reaction.

regards,
Markus

**Comment by bradleyjeck** [comment]
ok, very good.  There are some further updates in the dev version compared to what you would have gotten from CRAN.  One update is support for reading more sections of the inp file such as Reactions, which was not read before.

**Comment by gintaem** [comment]
thanks @bradleyjeck 
i already noticed by viewing the names of the read inp file.

**Comment by bradleyjeck** [comment]
I've posted another update into the main branch to issue a warning instead of an error when a section is repeated in the inp file.  This should allow you to also read inp files as before without editing them.
