### ISSUE TITLE
Plots with labels similar to EPANET

### ISSUE THREAD

**Issue by iembry-USGS** [bradleyjeck/epanetReader#31]
Is it possible for the plots to include the labels that are visible in the EPANET plots of the .inp files?

Thank you.

**Comment by bradleyjeck** [comment]
Hi @iembry-USGS - take a look at the new plotting method for inp objects.  Calling plot(inp, plot.labels=T) should add the labels from the inp file.

**Comment by iembry-USGS** [comment]
Hi @bradleyjeck  - Thank you for adding the new plotting method. Is this available in the version on CRAN?

**Comment by bradleyjeck** [comment]
Hi @iembry-USGS - this version is not on CRAN at the moment, but the plan is to put it there soon.  Have you had a chance to try it? devtools::install_github("bradleyjeck/epanetReader")

**Comment by iembry-USGS** [comment]
Hi @bradleyjeck - I'm sorry for my delay, but I just tried it out with your example. Thank you. It works.
