### ISSUE TITLE
write.inp function write Unbalanced STOP by default

### ISSUE THREAD

**Issue by mgomezgoiri** [bradleyjeck/epanetReader#37]
Dear Bradley,

We are trying to genete different ".inp" files authomaticaly. But we realize that, when we run them in Epanet collapse before finishing. We have been finding out why and we realize that "write.inp" function writes in [OPTIONS] "Unbalanced     STOP" by default. And we would like to choose the other option: "Unbalanced     Continue10". Is this possible in someway?

We are generating 100 individuals (inps) and it is a tedious work if we should do it one by one.

Thank you in advance,

**Comment by bradleyjeck** [comment]
Hi @mgomezgoiri, 

The value of the unbalanced option can be changed before you write the inp file.   For example
```
# see existing value of the option
Net1$Options$UNBALANCED
# change the value of the option
Net1$Options$UNBALANCED <- "Continue 10"
# see new value of the option
Net1$Options$UNBALANCED
```

Hope this helps,

Brad 

PS Did you see that there is a new package for running EPANET simulations directly in R? https://github.com/bradleyjeck/epanet2toolkit
