### ISSUE TITLE
Plot node by color instead of by size?

### ISSUE THREAD

**Issue by emmaliulu** [bradleyjeck/epanetReader#47]
Is it possible to color code my node value by adding a color attribute in plot?

plot(x, inp, Timestep = "24:00:00", juncQty = "AGE", 
     linkQty = "Flow", legend1.locn = "topright",
     legend2.locn = "topleft")

**Comment by bradleyjeck** [comment]
Hi @emmaliulu - Plotting nodes with colors is not supported in the current version of the package.   The good news is that R is great for creating highly customized plots.

A plot like what you describe can be built up from the info in the epanet.inp and epanet.rpt objects as follows:
* extract node values from rpt file  e.g.  `subset( rpt$nodeResults, Timestamp == "24:00:00", select = c("ID","AGE") ) 
* attach coordinates to the extracted node values using `merge()` with  inp$Coordinates 
* then plot the merged data using `points()` where you can specify the colors and node size etc.
* the structure of the network can be plotted by creating an `expandedLinkTable()` and plotting it.
