### ISSUE TITLE
read.inp does not work properly when mixing 001 and 1 nodes

### ISSUE THREAD

**Issue by petacoder75** [bradleyjeck/epanetReader#56]
If there are in the same INP-file nodes like 0001 and 1, depending on the topology of the network could happen that the read.inp function loads pipe$Node1 as character and pipe$Node2 as integer and vice-versa. This issue creates problems using functions like plot or expandedLinkTable, because the merge generates pipes without coordinates (NA value).

I think a solution could be that read.inp reads always the data as characters. I think force it would be a good solution.

Attached an example of a case where the problem appears.

[EpanetReaderBug.zip](https://github.com/bradleyjeck/epanetReader/files/2240252/EpanetReaderBug.zip)

**Comment by bradleyjeck** [comment]
@petacoder75 thanks for the bug report.  Looks like a fairly pathological case but I agree it should work. I'll try to push an update sometime.
